package com.freshprint.domain.summary;

import java.util.Objects;

/**
 * The current result of requesting a human-readable change summary.
 */
public sealed interface ChangeSummaryResult
    permits ChangeSummaryResult.Available,
    ChangeSummaryResult.Computing,
    ChangeSummaryResult.Unavailable {

  /**
   * Returns the summary availability exposed to a caller.
   *
   * @return available, computing, or unavailable
   */
  SummaryStatus status();

  /**
   * A summary that is ready to display.
   *
   * @param summary generated summary
   */
  record Available(ChangeSummary summary) implements ChangeSummaryResult {

    /**
     * Validates the generated summary.
     */
    public Available {
      Objects.requireNonNull(summary, "summary must not be null");
    }

    /**
     * Identifies this result as available.
     *
     * @return {@link SummaryStatus#AVAILABLE}
     */
    @Override
    public SummaryStatus status() {
      return SummaryStatus.AVAILABLE;
    }
  }

  /**
   * A summary that is still being generated by an asynchronous workflow.
   *
   * @param reason explanation or reason code
   */
  record Computing(String reason) implements ChangeSummaryResult {

    /**
     * Validates the reason.
     */
    public Computing {
      reason = requireReason(reason);
    }

    /**
     * Identifies this result as computing.
     *
     * @return {@link SummaryStatus#COMPUTING}
     */
    @Override
    public SummaryStatus status() {
      return SummaryStatus.COMPUTING;
    }
  }

  /**
   * A summary that could not be generated from the available data.
   *
   * @param reason explanation or reason code
   */
  record Unavailable(String reason) implements ChangeSummaryResult {

    /**
     * Validates the reason.
     */
    public Unavailable {
      reason = requireReason(reason);
    }

    /**
     * Identifies this result as unavailable.
     *
     * @return {@link SummaryStatus#UNAVAILABLE}
     */
    @Override
    public SummaryStatus status() {
      return SummaryStatus.UNAVAILABLE;
    }
  }

  /**
   * Returns a reason after checking that it contains text.
   *
   * @param reason reason to validate
   * @return validated reason
   */
  private static String requireReason(String reason) {
    Objects.requireNonNull(reason, "reason must not be null");
    if (reason.isBlank()) {
      throw new IllegalArgumentException("reason must not be blank");
    }
    return reason;
  }
}
